### ISSUE TITLE
You're ready to start testing 😎

### ISSUE THREAD

**Issue by arrested-developer** [FACxBeamery/project-week-3#32]
https://github.com/FACxBeamery/project-week-3/blob/4ff7f586fdd691e10bd668a5c43e97678cf7afad/test/test.js#L10

Great to see!

You can import the functions you've made in `lib/purefunctions.js` and test those with plenty of edge cases, that would be excellent!

We haven't looked at how to test the actual routes of a server yet but we might do next week.

**Comment by lyndseysc** [comment]
we just merged our testsuite branch! ( #31 )

**Comment by arrested-developer** [comment]
🙌🏻
