### ISSUE TITLE
handler / router confusion

### ISSUE THREAD

**Issue by arrested-developer** [FACxBeamery/project-week-3#33]
you seem to have the concepts of handler and router a bit mixed up...

The job of the router is to take the request and decide what to do with it - to **route** it to the correct function that can **handle** the request

You will likely have more than one **handler**, which will take the request, **handle** it, and then send back the response.

**Comment by Joaoviana** [comment]
Got it! will fix that asap

**Comment by Oliversw** [comment]
+1! We'll have a bit of a discussion about this later
