### ISSUE TITLE
Did you manage to get onto sanitising the input from the client (one of the stretch goals)?

### ISSUE THREAD

**Issue by TKostrzewski** [FACxBeamery/project-week-3#41]
I recognise that it was a stretch goal but I'd be very interested to see how it's done.

**Comment by TKostrzewski** [comment]
I like that you check for the request.method before handling the request.

**Comment by Joaoviana** [comment]
You could possibly test the string coming from your header/body with a regex. If there was a special character, get that same character and 'escape' it or replace it with its respective unicode!
